### ISSUE TITLE
Question: Why don't we have a defined struct for voting config?

### ISSUE THREAD

**Issue by marcvelmer** [aragon/core#11]
https://github.com/aragon/core/blob/43c69addb2c2aabcd56cc96d83b4b5841a41cb0e/packages/contracts/contracts/factories/DAOFactory.sol#L64

@nivida @brickpop Why don't we have a defined struct for voting config as we have `DAOConfigStruct`, `TokenConfigStruct` or `MintConfigStruct`?

Just asking because having the structs defined creates the correct typing for `ethers` library using `typechain` and can be imported in the SDK.

**Comment by novaknole** [comment]
Hi @marcvelmer 

I will include this on the next Merge.

**Comment by novaknole** [comment]
Hi @marcvelmer 

I made a PR (https://github.com/aragon/core/pull/20)

I was wondering if the changes are enough for you at this moment.
